spring:
  mail:
    host: smtp.yeah.net
    port: 25
    username: ai_edu@yeah.net
    password: TS2peY3YjSGYKdN9
    properties:
      mail:
        smtp: true
        starttls: true
  ai:
    openai:
      api-base-url: https://dify.aipfuture.com/v1
      api-key:  app-MCjlYzAxmtRZBGcEa9FpShDP


  datasource:
    url: jdbc:mysql://localhost:3306/stu_review?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 2 # 方便我调试
      timeout: 3000ms
#  kafka:
#    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
#    producer:
#      retries: 3
#      batch-size: 16384
#      buffer-memory: 33554432
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      enable-auto-commit: true
#      auto-commit-interval: 1000ms
#      group-id: group-1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    streams:
#      replication-factor: 3  # 设置流的副本数，确保流式数据的容错性
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.Entities
  global-config:
    db-config:
      id-type: auto  # 主键自增
      logic-delete-value: 1  # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0  # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动转换
server:
  port: 8008

logging:
  pattern:
    console: "%m%n"

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000  # 24小时，以毫秒为单位
dify:
  url: https://dify.aipfuture.com/v1
  key:
    ask-ai: app-oGCLThhvLjBwqnhzLbNnOure

springdoc:
  swagger-ui:
    path: /swagger-ui